/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ExpenseEntry = IDL.Record({
  'id' : IDL.Nat,
  'paymentMethod' : IDL.Nat,
  'date' : Time,
  'description' : IDL.Text,
  'vendor' : IDL.Nat,
  'category' : IDL.Nat,
  'amount' : IDL.Float64,
});
export const RevenueEntry = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'description' : IDL.Text,
  'category' : IDL.Nat,
  'amount' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createExpense' : IDL.Func([ExpenseEntry], [IDL.Nat], []),
  'createPaymentMethod' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createRevenue' : IDL.Func([RevenueEntry], [IDL.Nat], []),
  'createVendor' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deleteCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteExpense' : IDL.Func([IDL.Nat], [], []),
  'deletePaymentMethod' : IDL.Func([IDL.Nat], [], []),
  'deleteRevenue' : IDL.Func([IDL.Nat], [], []),
  'deleteVendor' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
      ['query'],
    ),
  'getExpenses' : IDL.Func([], [IDL.Vec(ExpenseEntry)], ['query']),
  'getPaymentMethods' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
      ['query'],
    ),
  'getRevenueEntries' : IDL.Func([], [IDL.Vec(RevenueEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVendors' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCategory' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateExpense' : IDL.Func([IDL.Nat, ExpenseEntry], [], []),
  'updatePaymentMethod' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateRevenue' : IDL.Func([IDL.Nat, RevenueEntry], [], []),
  'updateVendor' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ExpenseEntry = IDL.Record({
    'id' : IDL.Nat,
    'paymentMethod' : IDL.Nat,
    'date' : Time,
    'description' : IDL.Text,
    'vendor' : IDL.Nat,
    'category' : IDL.Nat,
    'amount' : IDL.Float64,
  });
  const RevenueEntry = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'description' : IDL.Text,
    'category' : IDL.Nat,
    'amount' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createExpense' : IDL.Func([ExpenseEntry], [IDL.Nat], []),
    'createPaymentMethod' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createRevenue' : IDL.Func([RevenueEntry], [IDL.Nat], []),
    'createVendor' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deleteCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteExpense' : IDL.Func([IDL.Nat], [], []),
    'deletePaymentMethod' : IDL.Func([IDL.Nat], [], []),
    'deleteRevenue' : IDL.Func([IDL.Nat], [], []),
    'deleteVendor' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
        ['query'],
      ),
    'getExpenses' : IDL.Func([], [IDL.Vec(ExpenseEntry)], ['query']),
    'getPaymentMethods' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
        ['query'],
      ),
    'getRevenueEntries' : IDL.Func([], [IDL.Vec(RevenueEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVendors' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCategory' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateExpense' : IDL.Func([IDL.Nat, ExpenseEntry], [], []),
    'updatePaymentMethod' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateRevenue' : IDL.Func([IDL.Nat, RevenueEntry], [], []),
    'updateVendor' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };