/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ExpenseEntry {
  'id' : bigint,
  'paymentMethod' : bigint,
  'date' : Time,
  'description' : string,
  'vendor' : bigint,
  'category' : bigint,
  'amount' : number,
}
export interface RevenueEntry {
  'id' : bigint,
  'date' : Time,
  'description' : string,
  'category' : bigint,
  'amount' : number,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCategory' : ActorMethod<[string], bigint>,
  'createExpense' : ActorMethod<[ExpenseEntry], bigint>,
  'createPaymentMethod' : ActorMethod<[string], bigint>,
  'createRevenue' : ActorMethod<[RevenueEntry], bigint>,
  'createVendor' : ActorMethod<[string], bigint>,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteExpense' : ActorMethod<[bigint], undefined>,
  'deletePaymentMethod' : ActorMethod<[bigint], undefined>,
  'deleteRevenue' : ActorMethod<[bigint], undefined>,
  'deleteVendor' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<[bigint, string]>>,
  'getExpenses' : ActorMethod<[], Array<ExpenseEntry>>,
  'getPaymentMethods' : ActorMethod<[], Array<[bigint, string]>>,
  'getRevenueEntries' : ActorMethod<[], Array<RevenueEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVendors' : ActorMethod<[], Array<[bigint, string]>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCategory' : ActorMethod<[bigint, string], undefined>,
  'updateExpense' : ActorMethod<[bigint, ExpenseEntry], undefined>,
  'updatePaymentMethod' : ActorMethod<[bigint, string], undefined>,
  'updateRevenue' : ActorMethod<[bigint, RevenueEntry], undefined>,
  'updateVendor' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];