/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ExpenseEntry = IDL.Record({
  'id' : IDL.Nat,
  'paymentMethod' : IDL.Text,
  'owner' : IDL.Principal,
  'bank' : IDL.Opt(IDL.Nat),
  'date' : Time,
  'description' : IDL.Text,
  'vendor' : IDL.Nat,
  'category' : IDL.Nat,
  'amount' : IDL.Float64,
});
export const RevenueEntry = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'date' : Time,
  'description' : IDL.Text,
  'category' : IDL.Nat,
  'amount' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CogsItem = IDL.Record({
  'id' : IDL.Nat,
  'defaultUnitCost' : IDL.Float64,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'vendor' : IDL.Opt(IDL.Nat),
});
export const CogsPurchase = IDL.Record({
  'id' : IDL.Nat,
  'itemId' : IDL.Nat,
  'purchaseDate' : Time,
  'owner' : IDL.Principal,
  'vendor' : IDL.Opt(IDL.Nat),
  'quantity' : IDL.Float64,
  'unitCost' : IDL.Float64,
});
export const CogsSale = IDL.Record({
  'id' : IDL.Nat,
  'itemId' : IDL.Nat,
  'owner' : IDL.Principal,
  'quantity' : IDL.Float64,
  'saleDate' : Time,
});
export const YearMonthBucket = IDL.Record({
  'month' : IDL.Nat,
  'year' : IDL.Int,
});
export const UserInfo = IDL.Record({
  'principal' : IDL.Principal,
  'role' : UserRole,
});
export const LoginCredentials = IDL.Record({
  'password' : IDL.Text,
  'employeeId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateCogsForPeriod' : IDL.Func([Time, Time], [IDL.Float64], ['query']),
  'changeUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBank' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createCategory' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createCogsItem' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'createCogsPurchase' : IDL.Func(
      [IDL.Nat, Time, IDL.Float64, IDL.Float64, IDL.Opt(IDL.Nat)],
      [IDL.Nat],
      [],
    ),
  'createCogsSale' : IDL.Func([IDL.Nat, Time, IDL.Float64], [IDL.Nat], []),
  'createExpense' : IDL.Func([ExpenseEntry], [IDL.Nat], []),
  'createRevenue' : IDL.Func([RevenueEntry], [IDL.Nat], []),
  'createVendor' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deleteBank' : IDL.Func([IDL.Nat], [], []),
  'deleteCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteCogsItem' : IDL.Func([IDL.Nat], [], []),
  'deleteCogsPurchase' : IDL.Func([IDL.Nat], [], []),
  'deleteCogsSale' : IDL.Func([IDL.Nat], [], []),
  'deleteExpense' : IDL.Func([IDL.Nat], [], []),
  'deleteRevenue' : IDL.Func([IDL.Nat], [], []),
  'deleteVendor' : IDL.Func([IDL.Nat], [], []),
  'getBanks' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
      ['query'],
    ),
  'getCogsItems' : IDL.Func([], [IDL.Vec(CogsItem)], ['query']),
  'getCogsPurchases' : IDL.Func([], [IDL.Vec(CogsPurchase)], ['query']),
  'getCogsSales' : IDL.Func([], [IDL.Vec(CogsSale)], ['query']),
  'getCogsTrends' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(YearMonthBucket, IDL.Float64))],
      ['query'],
    ),
  'getCurrentRole' : IDL.Func(
      [],
      [
        IDL.Variant({
          'unauthenticated' : IDL.Null,
          'authenticated' : UserRole,
        }),
      ],
      ['query'],
    ),
  'getExpenses' : IDL.Func([], [IDL.Vec(ExpenseEntry)], ['query']),
  'getPaymentMethods' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getRevenueEntries' : IDL.Func([], [IDL.Vec(RevenueEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVendors' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(UserInfo)], ['query']),
  'loginWithCredentials' : IDL.Func([LoginCredentials], [UserRole], []),
  'logout' : IDL.Func([], [], []),
  'registerCredentials' : IDL.Func([IDL.Nat, IDL.Text, UserRole], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBank' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateCategory' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateCogsItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'updateCogsPurchase' : IDL.Func(
      [IDL.Nat, IDL.Nat, Time, IDL.Float64, IDL.Float64, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'updateCogsSale' : IDL.Func([IDL.Nat, IDL.Nat, Time, IDL.Float64], [], []),
  'updateExpense' : IDL.Func([IDL.Nat, ExpenseEntry], [], []),
  'updateRevenue' : IDL.Func([IDL.Nat, RevenueEntry], [], []),
  'updateVendor' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ExpenseEntry = IDL.Record({
    'id' : IDL.Nat,
    'paymentMethod' : IDL.Text,
    'owner' : IDL.Principal,
    'bank' : IDL.Opt(IDL.Nat),
    'date' : Time,
    'description' : IDL.Text,
    'vendor' : IDL.Nat,
    'category' : IDL.Nat,
    'amount' : IDL.Float64,
  });
  const RevenueEntry = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'date' : Time,
    'description' : IDL.Text,
    'category' : IDL.Nat,
    'amount' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CogsItem = IDL.Record({
    'id' : IDL.Nat,
    'defaultUnitCost' : IDL.Float64,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'vendor' : IDL.Opt(IDL.Nat),
  });
  const CogsPurchase = IDL.Record({
    'id' : IDL.Nat,
    'itemId' : IDL.Nat,
    'purchaseDate' : Time,
    'owner' : IDL.Principal,
    'vendor' : IDL.Opt(IDL.Nat),
    'quantity' : IDL.Float64,
    'unitCost' : IDL.Float64,
  });
  const CogsSale = IDL.Record({
    'id' : IDL.Nat,
    'itemId' : IDL.Nat,
    'owner' : IDL.Principal,
    'quantity' : IDL.Float64,
    'saleDate' : Time,
  });
  const YearMonthBucket = IDL.Record({ 'month' : IDL.Nat, 'year' : IDL.Int });
  const UserInfo = IDL.Record({
    'principal' : IDL.Principal,
    'role' : UserRole,
  });
  const LoginCredentials = IDL.Record({
    'password' : IDL.Text,
    'employeeId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateCogsForPeriod' : IDL.Func([Time, Time], [IDL.Float64], ['query']),
    'changeUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBank' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createCategory' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createCogsItem' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'createCogsPurchase' : IDL.Func(
        [IDL.Nat, Time, IDL.Float64, IDL.Float64, IDL.Opt(IDL.Nat)],
        [IDL.Nat],
        [],
      ),
    'createCogsSale' : IDL.Func([IDL.Nat, Time, IDL.Float64], [IDL.Nat], []),
    'createExpense' : IDL.Func([ExpenseEntry], [IDL.Nat], []),
    'createRevenue' : IDL.Func([RevenueEntry], [IDL.Nat], []),
    'createVendor' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deleteBank' : IDL.Func([IDL.Nat], [], []),
    'deleteCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteCogsItem' : IDL.Func([IDL.Nat], [], []),
    'deleteCogsPurchase' : IDL.Func([IDL.Nat], [], []),
    'deleteCogsSale' : IDL.Func([IDL.Nat], [], []),
    'deleteExpense' : IDL.Func([IDL.Nat], [], []),
    'deleteRevenue' : IDL.Func([IDL.Nat], [], []),
    'deleteVendor' : IDL.Func([IDL.Nat], [], []),
    'getBanks' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
        ['query'],
      ),
    'getCogsItems' : IDL.Func([], [IDL.Vec(CogsItem)], ['query']),
    'getCogsPurchases' : IDL.Func([], [IDL.Vec(CogsPurchase)], ['query']),
    'getCogsSales' : IDL.Func([], [IDL.Vec(CogsSale)], ['query']),
    'getCogsTrends' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(YearMonthBucket, IDL.Float64))],
        ['query'],
      ),
    'getCurrentRole' : IDL.Func(
        [],
        [
          IDL.Variant({
            'unauthenticated' : IDL.Null,
            'authenticated' : UserRole,
          }),
        ],
        ['query'],
      ),
    'getExpenses' : IDL.Func([], [IDL.Vec(ExpenseEntry)], ['query']),
    'getPaymentMethods' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getRevenueEntries' : IDL.Func([], [IDL.Vec(RevenueEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVendors' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(UserInfo)], ['query']),
    'loginWithCredentials' : IDL.Func([LoginCredentials], [UserRole], []),
    'logout' : IDL.Func([], [], []),
    'registerCredentials' : IDL.Func([IDL.Nat, IDL.Text, UserRole], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBank' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateCategory' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateCogsItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'updateCogsPurchase' : IDL.Func(
        [IDL.Nat, IDL.Nat, Time, IDL.Float64, IDL.Float64, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'updateCogsSale' : IDL.Func([IDL.Nat, IDL.Nat, Time, IDL.Float64], [], []),
    'updateExpense' : IDL.Func([IDL.Nat, ExpenseEntry], [], []),
    'updateRevenue' : IDL.Func([IDL.Nat, RevenueEntry], [], []),
    'updateVendor' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };